name: lernen
description: "Learn German With AI Assistance. Developed Bismark Kessie"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 3.1.5+2

environment:
  sdk: ^3.5.0

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.8
  dropdown_search: ^6.0.1
  flutter:
    sdk: flutter
  flutter_beep: ^1.0.0
  flutter_svg: ^2.0.10+1
  flutter_tts: 
  get: ^4.6.6
  pocketbase: ^0.21.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  flutter_dotenv:
  http: ^1.2.2
  sqflite:
  google_fonts:
  flutter_markdown:
  html2md:
  sqflite_common_ffi_web:
  intl:
  flutter_launcher_icons:

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/logo/logo.png"
    min_sdk_android: 21 # android min sdk min:16, default 21
    web:
      generate: true
      image_path: "assets/logo/logo.png"
      background_color: "#hexcode"
      theme_color: "#hexcode"
    windows:
      generate: true
      image_path: "assets/logo/logo.png"
      icon_size: 48 # min:48, max:256, default: 48
    macos:
      generate: true
      image_path: "assets/logo/logo.png"

  

flutter:
  uses-material-design: true
  assets:
    - assets/dict.json
    - assets/svg/
    - .env
    - assets/logo/logo.png
