name: lernen
description: "Learn German With AI Assistance. Developed Bismark Kessie"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 3.1.3+0

environment:
  sdk: ^3.5.0

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.8
  dropdown_search: ^6.0.1
  flutter:
    sdk: flutter
  flutter_beep: ^1.0.0
  flutter_svg: ^2.0.10+1
  flutter_tts: 
  get: ^4.6.6
  pocketbase: ^0.18.1
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  flutter_dotenv:
  http: ^1.2.2
  sqflite:
  google_fonts:
  flutter_markdown:
  html2md:
  sqflite_common_ffi_web:
  intl:
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/dict.json
    - assets/svg/
    - .env
