name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: 
          java-version: "21"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Create .env file
        run: |
          echo "POCKETBASE_API=${{ secrets.POCKETBASE_API }}" > .env
          echo "AIAPI=${{ secrets.AIAPI }}" >> .env
      - run: flutter pub get
      - run: flutter analyze

  build_ios:
    name: Build Flutter (iOS)
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-java@v1
        with: 
          java-version: "21"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          cp -r ../Runner.app .
          cd ..
          zip -r Runner.ipa Payload
      - name: Upload to App Store
        uses: appleboy/app-store-action@v0.3.0
        with:
          app_id: ${{ secrets.APP_STORE_APP_ID }}
          api_key_id: ${{ secrets.APP_STORE_API_KEY_ID }}
          api_key_issuer_id: ${{ secrets.APP_STORE_API_KEY_ISSUER_ID }}
          api_key: ${{ secrets.APP_STORE_API_KEY }}
          ipa_path: build/ios/iphoneos/Runner.ipa
